AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/umts-custom-cops/version.rb'

Naming/FileName:
  Enabled: false
