language: ruby
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
env: CODECLIMATE_REPO_TOKEN=c356c22cc5b342d3cba9a1fb9d71b63b52de9b9daa1f54c07f959f90da05c8ff
before_install: gem install bundler -v "$(cat .bundler.version)"
script: 
  - bundle exec rake
after_success:
  - bundle exec codeclimate-test-reporter
notifications:
  email:
    on_success: change
    on_failure: change
    recipients:
      - transit-it@admin.umass.edu
