language: ruby
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
env: CODECLIMATE_REPO_TOKEN=c356c22cc5b342d3cba9a1fb9d71b63b52de9b9daa1f54c07f959f90da05c8ff
before_install:
  - gem install bundler -v "$(cat .bundler.version)"
script:
  - bundle "_$(cat .bundler.version)_" exec rake
after_success:
  - bundle "_$(cat .bundler.version)_" exec codeclimate-test-reporter
notifications:
  email:
    on_success: change
    on_failure: change
    recipients:
      - transit-it@admin.umass.edu
